#if UNITY_ANDROID
using System.Collections;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

public class AndroidBuildSettings
{

	[PostProcessBuild]
	public static void OnPostprocessBuild(BuildTarget buildTarget, string pathToBuiltProject)
	{
		var webClientId = GooglePlayGames.GameInfo.WebClientId;
		var manifest = GetManifest(webClientId);
		WriteFile(ManifestPath, manifest);
	}

	private static string GetManifest(string webClientId)
	{
		return string.Format(TemplateFile, webClientId);
	}

	private static void WriteFile(string path, string body)
	{
		FileInfo fi = new FileInfo(path);
		Directory.CreateDirectory(fi.DirectoryName);

		using(var wr = new StreamWriter(path, false))
		{
			wr.Write(body);
		}
	}

	private const string ManifestPath = @"Assets/Zapic/Plugins/Android/ZapicManifest.plugin/AndroidManifest.xml";

	private const string TemplateFile = @"<?xml version = ""1.0"" encoding=""utf-8""?>
<!-- This file was automatically generated by the Zapic SDK for Unity.Do not edit. -->
<manifest xmlns:android=""http://schemas.android.com/apk/res/android""
    package=""com.zapic.sdk.android.unity""
    android:versionCode=""1""
    android:versionName=""1.0"" >

    <uses-sdk android:minSdkVersion=""8"" android:targetSdkVersion=""16"" />

    <application>
		<meta-data android:name=""com.google.android.gms.games.WEB_CLIENT_ID"" android:value=""{0}"" />
    </application>
</manifest>";
}

#endif