using System.IO;
using UnityEditor;
using UnityEngine;

class ZapicEditorWindow : EditorWindow
{
    private string _appId = "";

    private const string ManifestPath = @"Assets/Zapic/Plugins/Android/ZapicManifest.plugin/AndroidManifest.xml";

    private const string TemplateFile = @"<?xml version = ""1.0"" encoding=""utf-8""?>
<!-- This file was automatically generated by the Zapic SDK for Unity.Do not edit. -->
<manifest xmlns:android=""http://schemas.android.com/apk/res/android""
    package=""com.zapic.sdk.android.unity""
    android:versionCode=""1""
    android:versionName=""1.0"" >

    <uses-sdk android:minSdkVersion=""8"" android:targetSdkVersion=""16"" />

    <application>
        <meta-data android:name=""com.google.android.gms.games.APP_ID"" android:value=""{0}"" />
    </application>
</manifest>";

    [MenuItem("Window/Zapic")]
    public static void ShowZapicMenu()
    {
        EditorWindow.GetWindow(typeof(ZapicEditorWindow), true, "Zapic");
    }

    void OnGUI()
    {
        GUI.skin.label.wordWrap = true;
        GUILayout.BeginVertical();

        GUIStyle link = new GUIStyle(GUI.skin.label);
        link.normal.textColor = new Color(0f, 0f, 1f);

        GUILayout.Space(10);

        GUILayout.Label("To configure Zapic in Android apps, get the App Id from the Google Play Console, enter it below and click configure");

        if (GUILayout.Button("Open Play Games Console", link, GUILayout.ExpandWidth(false)))
        {
            Application.OpenURL("https://play.google.com/apps/publish");
        }

        GUILayout.Space(10);

        _appId = EditorGUILayout.TextField(
            "AppId",
            _appId);

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.FlexibleSpace();
        if (GUILayout.Button("Configure", GUILayout.Width(100)))
        {
            ConfigureSDK();
        }

        if (GUILayout.Button("Cancel", GUILayout.Width(100)))
        {
            Close();
        }

        GUILayout.FlexibleSpace();
        GUILayout.EndHorizontal();
        GUILayout.Space(20);
        GUILayout.EndVertical();
    }

    private string GetManifest(string appId)
    {
        return string.Format(TemplateFile, appId);
    }

    private void ConfigureSDK()
    {
        if (string.IsNullOrEmpty(_appId))
        {
            Debug.LogError("Please set a valid AppId prior to configuring Zapic for Android.");
            return;
        }

        var manifest = GetManifest(_appId);

        Debug.LogFormat("Saving new android manifest to {0}", ManifestPath);

        WriteFile(ManifestPath, manifest);
    }

    public static void WriteFile(string path, string body)
    {
        FileInfo fi = new FileInfo(path);
        Directory.CreateDirectory(fi.DirectoryName);

        using (var wr = new StreamWriter(path, false))
        {
            wr.Write(body);
        }
    }
}